limit_req_status 429;
limit_req_zone $binary_remote_addr zone=movableq:10m rate=5r/s;

server {
    listen 80;
    listen [::]:80;

    server_name @domain@ www.@domain@;

    location / {
        return 301 https://@domain@$request_uri;
    }
}

server {
    listen 443 default_server ssl;
    listen [::]:443 ssl;

    server_name @domain@ www.@domain@;

    location / {
        root /usr/share/nginx/html/default/;
        try_files $uri $uri.html $uri/ =404;
    }

    # Matrix
    location /.well-known/matrix/client {
        return 200 '{"m.homeserver": {"base_url": "https://matrix.@domain@"}}';
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }
    location /.well-known/matrix/server {
        return 200 '{"m.server": "matrix.@domain@:443"}';
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }

    # Discord
    location /.well-known/discord {
        return 200 'dh=c99814f21544c604b6e302333e8b6df917218efc';
        default_type text/html;
        add_header Access-Control-Allow-Origin *;

    }

    location /movableq/ {
        proxy_pass http://host.containers.internal:7799/;
        # https://flask.palletsprojects.com/en/2.2.x/deploying/nginx/
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /movableq/;
    }
}
