#!/usr/bin/env bash


# Enter appropriate home manager directory
pushd "$HOME/.nixos-configs/home-manager/homes/$(hostname)_$(whoami)" > /dev/null
# Start with blank line for formatting
echo

# Track all files in repo
git add -AN


# Update flake inputs

if [[ "$1" == "--update" ]]; then
    gum spin --spinner line --title "Updating flake inputs..." -- \
        sh -c 'nix flake update &> flake-update.log'

    if [[ $? -ne 0 ]]; then
        echo -e "🚫 Flake update failed, see the log for details.\n"

        read -p "Press [enter] to continue..."
        cat flake-update.log | gum pager

        popd > /dev/null
        exit 1
    fi

    echo -e "❄️ Flake inputs are up-to-date.\n"
fi


# Check if changes are present

if git diff --quiet; then
    echo -e "💤 No changes, exiting.\n"

    popd > /dev/null
    exit 0
fi


# Home Manager rebuild

gum spin --spinner line --title "Rebuilding..." -- \
    sh -c 'home-manager switch --flake . &> hm-switch.log'

if [[ $? -ne 0 ]]; then
    echo -e "🚫 Rebuild failed, see the log for details.\n"

    read -p "Press [enter] to continue..."
    cat hm-switch.log | gum pager

    popd > /dev/null
    exit 1
fi

echo -e "🏠 Rebuild successful!\n"


# Show rebuild results

home-manager generations | head -n 1 | awk '{
    printf "  Generation : %s\n", $5
    printf "  Build Date : %s\n", $1 " " $2
    printf "\n"
}'

# git diff --color | gum pager

popd > /dev/null
