#!/usr/bin/env bash

DEVSHELL_PATH=./.nix-shell

mkdir "$DEVSHELL_PATH"

cat << EOF > "$DEVSHELL_PATH/flake.nix"
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs =
    { self, nixpkgs }:
    let
      pkgs = import nixpkgs {
        system = "x86_64-linux";
        config.allowUnfree = true;
      };
    in
    {
      devShells.x86_64-linux.default = pkgs.mkShell {
        packages = with pkgs; [
        ];
      };
    };
}
EOF

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
	git add -f "$DEVSHELL_PATH"
fi

nix flake update --flake "$DEVSHELL_PATH"

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
	git rm -r --cached "$DEVSHELL_PATH"
fi

echo "use flake path:$DEVSHELL_PATH" > .envrc
direnv allow
